[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/backend/*"
  to = "http://52.67.144.140:8080/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
